# Generated by Django 3.0.5 on 2020-04-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('edad', models.IntegerField(null=True)),
                ('correo', models.CharField(max_length=40, verbose_name='correo')),
                ('telefono', models.CharField(max_length=100, verbose_name='telefono')),
                ('usuario', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='usuario')),
                ('contrasenia', models.CharField(max_length=100, verbose_name='contrasenia')),
                ('foto', models.BinaryField()),
            ],
        ),
    ]
