# Generated by Django 3.0.5 on 2020-04-30 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparchar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('idcalificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('porcentaje', models.FloatField(null=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('multimedia', models.CharField(max_length=100, null=True)),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('usuariocliente', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='apparchar.cliente')),
            ],
        ),
    ]
