# Generated by Django 3.0.5 on 2020-04-30 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparchar', '0002_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparchar.Calificacion')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparchar.Evento')),
            ],
        ),
    ]
