# Generated by Django 3.0.5 on 2020-04-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparchar', '0003_remove_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.CharField(max_length=100, null=True, verbose_name='foto'),
        ),
    ]
