# Generated by Django 3.0.5 on 2020-05-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparchar', '0004_auto_20200502_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparchar.Evento'),
        ),
    ]
